export const refs = {
  mainList: document.querySelector('.js-main-film-list'),
  dataNotFoundEl: document.querySelector('.js-not-film-card'),
  headerForm: document.querySelector('.header__form'),
  authBtn: document.querySelector('.auth-btn'),
  footerBtn: document.querySelector('.footer__btn'),
  loader: document.querySelector(`.js-page-loader`),
  headerWatchedBtn: document.querySelector('.js-watched'),
  headerQueueBtn: document.querySelector('.js-queue'),
  paginationBox: document.querySelector('.pagination_box'),
  trendingSection: document.querySelector('.swiper-section'),
  btnToTop: document.querySelector('.up-btn'),
  aboutModal: document.querySelector('.js-about-modal'),
  body: document.querySelector('body'),
  swiperModal: document.querySelector('#swiper-modal'),
  libBtn: document.querySelector('.library__btns'),
  modal: document.querySelector('[data-backdrop]'),
  dataBackdrop: document.querySelector('[data-backdrop]'),
  changeTheme: document.querySelectorAll(`.change_theme`),
  changeThemeCssLink: document.querySelector(`[title="theme"]`),
  swiperWrapper: document.querySelector('.swiper-wrapper'),
  swiperRef: document.querySelector('#trends-swiper'),
  autorizationChecked: document.querySelector('.icon-autorization-checked'),
  autorization: document.querySelector('.icon-autorization'),
  foterLink: document.querySelector('.footer__link'),
  userStatus: document.querySelector('.js-userStatus'),
};
